mysite/bank/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('bank', views.add_bank, name='bank'),
    path('branch', views.add_branch, name='branch'),
    path('branch-list', views.branch_list, name='branch-list'),
    path('load-taluka', views.load_taluka, name='load-taluka'),
]

mysite/district/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('district', views.add_district, name='district'),
    path('taluka', views.add_taluka, name='taluka'),
    path('village', views.add_village, name='village'),
    path('load-taluka', views.load_taluka, name='load-taluka'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    # path('', include('administration.urls')),
    path('district/', include('district.urls')),
    path('bank/', include('bank.urls')),
    path('', include('account.urls')),
    path('administration/', include('administration.urls')),
    path('employee/', include('employee.urls')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/customer/models.py
from django.db import models
from district.models import District, Taluka, Village
from bank.models import Bank, Branch
# Create your models here.


class AddressInfo(models.Model):
    address = models.TextField(max_length=355, null=True)
    landmark = models.TextField(max_length=355, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    taluka = models.ForeignKey(Taluka, on_delete=models.CASCADE, null=True)
    village = models.TextField(null=True)

    def __str__(self):
        return self.village

class BankInfo(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)




class Customer(models.Model):
    name = models.CharField(max_length=300, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

mysite/district/models.py
from django.db import models

# Create your models here.

class District(models.Model):
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Taluka(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Village(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    taluka = models.ForeignKey(Taluka, on_delete=models.CASCADE)
    name = models.CharField(max_length=45, unique=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

mysite/district/forms.py
from django import forms

from . import models
from .models import District, Taluka, Village


class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class TalukaForm(forms.ModelForm):
    class Meta:
        model = Taluka
        fields = '__all__'
        widgets = {
            'district': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class VillageForm(forms.ModelForm):
    class Meta:
        model = Village
        fields = '__all__'
        widgets = {
            'district': forms.Select(attrs={'class': 'form-control'}),
            'taluka': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['taluka'].queryset = models.Taluka.objects.none()

        if 'taluka' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['taluka'].queryset = models.Taluka.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['taluka'].queryset = self.instance.district.taluka_set.order_by('name')

        # self.fields['village'].queryset = models.Village.objects.none()
        #
        # if 'village' in self.data:
        #     try:
        #         taluka_id = int(self.data.get('taluka'))
        #         self.fields['village'].queryset = models.Village.objects.filter(taluka_id=taluka_id).order_by('name')
        #     except (ValueError, TypeError):
        #         pass
        # elif self.instance.pk:
        #     self.fields['union'].queryset = self.instance.taluka.village_set.order_by('name')

mysite/district/views.py
from django.shortcuts import render, redirect
from .models import District, Taluka, Village
from .forms import DistrictForm, TalukaForm, VillageForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def load_taluka(request):
    district_id = request.GET.get('district')
    print('....................')
    print(district_id)
    taluka = Taluka.objects.filter(district_id=district_id).order_by('name')
    context = {
        'taluka': taluka
    }
    return render(request, 'other/taluka_dropdown_list_options.html', context)


@login_required(login_url='login')
def load_village(request):
    taluka_id = request.GET.get('taluka')
    village = Village.objects.filter(taluka_id=taluka_id).order_by('name')
    context = {
        'village': village
    }
    return render(request, 'others/village_dropdown_list_options.html', context)


@login_required(login_url='login')
def add_district(request):
    forms = DistrictForm()
    if request.method == 'POST':
        forms = DistrictForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('district')
    district = District.objects.all()
    context = {'forms': forms, 'district': district}
    return render(request, 'district/district.html', context)


@login_required(login_url='login')
def add_taluka(request):
    forms = TalukaForm()
    if request.method == 'POST':
        forms = TalukaForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('taluka')
    taluka = Taluka.objects.all()
    context = {'forms': forms, 'taluka': taluka}
    return render(request, 'district/taluka.html', context)


@login_required(login_url='login')
def add_village(request):
    forms = VillageForm()
    if request.method == 'POST':
        forms = VillageForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('village')
    village = Village.objects.all()
    context = {'forms': forms, 'village': village}
    return render(request, 'district/village.html', context)


@login_required(login_url='login')
def load_taluka(request):
    district_id = request.GET.get('district')
    taluka = Taluka.objects.filter(district_id=district_id).order_by('name')

    taluka_id = request.GET.get('taluka')
    village = Village.objects.filter(taluka_id=taluka_id).order_by('name')
    context = {
        'taluka': taluka,
        'village': village
    }
    return render(request, 'others/taluka_dropdown_list_options.html', context)

mysite/templates/district/district.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header">District Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>District List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>District Name</th>
                      <th>Register Date</th>
                  </tr>
              </thead>
              <tbody>
                  {% for district in district %}
                    <tr>
                        <td>{{ district.id }}</td>
                        <td>{{ district.name }}</td>
                        <td>{{ district.date }}</td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
{% endblock %}

mysite/templates/district/taluka.html
{% extends 'base/base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header">Taluka Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Taluka List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>Taluka Name</th>
                      <th>Register Date</th>
                  </tr>
              </thead>
              <tbody>
                  {% for taluka in taluka %}
                    <tr>
                        <td>{{ taluka.id }}</td>
                        <td>{{ taluka.name }}</td>
                        <td>{{ taluka.date }}</td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
{% endblock %}

mysite/templates/district/village.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Village Register Form</div>
    <div class="card-body">
      <form class="" action="" method="post"   id="VillageRegistrationForm" data-taluka-url={% url 'load-taluka' %}>
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!--      <script src="{% static 'src/js/registration.js' %}"></script>-->
<!--      <script src="{% static 'src/js/address.js' %}"></script>-->
        <script>
        $("#id_district").change(function () {
          var url = $("#VillageRegistrationForm").attr("data-taluka-url");
          var districtId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'district': districtId
            },
            success: function (data) {
              $("#id_taluka").html(data);
            }
          });

        });
        $("#id_taluka").change(function () {
          var url = $("#VillageRegistrationForm").attr("data-taluka-url");
          var talukaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'taluka': talukaId
            },
            success: function (data) {
              $("#id_village").html(data);
            }
          });

        });
      </script>

    </div>
  </div>

  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Union List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                      <th>Id</th>
                      <th>Village Name</th>
                      <th>Register Date</th>
                  </tr>
              </thead>
              <tbody>
                  {% for village in village %}
                    <tr>
                        <td>{{ village.id }}</td>
                        <td>{{ village.name }}</td>
                        <td>{{ village.date }}</td>
                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
{% endblock %}